name: Deploy React Project to Running EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EC2 instance using SSH
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key ubuntu@${{ secrets.SSH_HOST }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          cd test-react-project/react-app
          npm install

      - name: Build and run React app
        run: |
          npm run dev
